### ISSUE TITLE
Command does not exist

### ISSUE THREAD

**Issue by 0xechan** [Afanyiyu/vscode-types-for-adobe#1]
adding the extendscript pack and trying to run the command results in "no matching commands."

**Comment by ilharp** [comment]
Open a folder, create an `.jsx` file, open it, and try to run the command again.

**Comment by 0xechan** [comment]
Right, I already did that when I posted this.

![image](https://user-images.githubusercontent.com/85286825/135861022-fae2c4f2-ee26-4649-a728-f262396863b3.png)
![image](https://user-images.githubusercontent.com/85286825/135861078-07155dd2-971e-4eb2-ad0b-825866864cd8.png)
![image](https://user-images.githubusercontent.com/85286825/135861671-423de340-9244-4fba-a5e8-f8c9952125e1.png)

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/135862053-e3528db5-d61b-4bb8-9c0e-03e7e78a471c.png)

Weird. Even if there is no `Set-Up Types for Adobe` command, `> Types` should be able to match several commands of TypeScript plugin, because TypeScript is a built-in plugin for VSCode.

Please try to check if there is a problem with your VSCode installation, or if some "untrusted workspace" features are enabled.

**Comment by 0xechan** [comment]
Sorry, I assumed there were no requirements. This said that typescript wasn't required. I will play a bit with that and see if it fixes anything. Thank you!


```
Requirements

Zero. No need for Node.js, TypeScript or Git.
```

**Comment by ilharp** [comment]
There's no need for TypeScript because **TypeScript is a built-in plugin of VSCode.**

In other words, as long as you've installed VSCode, you should already have the built-in TypeScript plugin and you don't need to install TypeScript.

If your VSCode does not have a TypeScript plug-in, there may be a problem with your **VSCode installation**.

**Comment by Ryah** [comment]
### **EDIT:** 

I figured out the issue. I also have the ExtendScript extension installed, which changes the language to "ExtendScript" instead of "TypeScript" for jsx files. Thus making the command not appear at all since the document isn't a TypeScript or Javascript file according to VSCode, it's an ExtendScript file. 

![image](https://user-images.githubusercontent.com/14987609/139894821-f9f357f4-263f-4afc-bf11-9d738701b62e.png)

I'll make a PR with the fix to make the command show, but I'm not sure about the types actually _working_. For now, the only way I can show types is by switching the language to "Javascript" after making the jsx file.

---
<details>
  <summary>Original Comment</summary>
I know I'm a bit late but for me, the command only shows up when I have a file open with the ".js" extension. A file with the ".jsx" extension won't show the command. 

@etheria-chan I recommend trying that if you haven't figured it out already.

---

![image](https://user-images.githubusercontent.com/14987609/139889333-14aeaac6-6a46-4f21-aad2-51b5c5e5fbcc.png)
![image](https://user-images.githubusercontent.com/14987609/139889512-4b21720c-6b54-4213-bb7c-5c1f5e96befd.png)
</details>

**Comment by ilharp** [comment]
Thanks @Ryah , it seems that this is caused by [Hennamann/ExtendScript-for-Visual-Studio-Code](https://github.com/Hennamann/ExtendScript-for-Visual-Studio-Code) (a.k.a. plugin [`ExtendScript`](https://github.com/Hennamann/ExtendScript-for-Visual-Studio-Code)).

---

https://github.com/Hennamann/ExtendScript-for-Visual-Studio-Code/blob/master/package.json#L22-L35

```json
"languages": [
    {
        "id": "jsx",
        "aliases": [
            "ExtendScript",
            "jsx"
        ],
        "extensions": [
            ".jsx",
            ".jsxinc"
        ],
        "configuration": "./language-configuration.json"
    }
],
```

---

My plugin is designed to use the VSCode built-in `TypeScript` plugin to implement its functions such as type checking and IntelliSense, but [`ExtendScript`](https://github.com/Hennamann/ExtendScript-for-Visual-Studio-Code) prevents the `TypeScript` plug-in from inspecting the `jsx` file. In my opinion, I don't recommend using the [`ExtendScript`](https://github.com/Hennamann/ExtendScript-for-Visual-Studio-Code) plugin.

I'll merge #2 to make `Set-Up` command work, but I won't guarantee that type checking and IntelliSense will work.

**Comment by ilharp** [comment]
Version `0.1.1` published. If the problem persists, please reopen this issue.
